################################################################################
# Script to explore: how the maximum probability that a first recurrence is a
# recrudescence / reinfection varies with MOI vectors given data on the
# enrolment episode and the first recurrence only. The figures generated by this
# script feature in graph-prior.tex.
################################################################################
rm(list = ls())
load("../data/maxima.rda")
all_MOIs <- sapply(colnames(maxima), function(x) as.numeric(strsplit(x, split = "")[[1]]))
maxMOIs <- sapply(all_MOIs, function(x) max(x))
logit <- function(x) log(x/(1-x))

# ==============================================================================
# General understanding of maximum probabilities
# ==============================================================================
nMOI <- sapply(all_MOIs, function(x) length(x)) # Number of episodes
MOI1 <- sapply(all_MOIs, function(x) x[1]) # MOI of episode one
MOI2 <- sapply(all_MOIs, function(x) x[2]) # MOI of episode two
MOI12diff <- sapply(all_MOIs, function(x) x[1] - x[2]) # Difference
MOI1s_log <- sapply(all_MOIs, function(x) all(x == 1)) # MOI vectors of all 1s
Episode_counts <- sort(unique(nMOI))

# Cases where the MOI is always one
plot(x = nMOI[MOI1s_log], y = maxima["theory_C_with", MOI1s_log], bty = "n",
     type = "b", main = "", bg = "yellow", pch = 24, ylim = c(0.5, 1),
     xlab = "Number of monoclonal episodes",
     ylab = "Maximum probability of first recurrence")
lines(x = nMOI[MOI1s_log], y = maxima["theory_I_with", MOI1s_log],
      type = "b", bg = "red", pch = 25)
legend("top", legend = c("Recrudescence", "Reinfection"), pch = c(24, 25),
       bt = "n", pt.bg = c("red", "yellow"))

# Imbalance between episodes one and two

plot(x = MOI12diff, y = maxima["theory_C_with", ], ylim = c(0.5, 1), bty = "n",
     col = MOI1, pch = as.character(nMOI),
     ylab = "Maximum probability of recrudescence",
     xlab = "MOI episode 1 - MOI episode 2"
text(y = 0.5, x = 2, adj = 1,
     labels = paste0("Number of episodes: ", paste(Episode_counts, collapse = " ")))
legend("left", title = "MOI of episode 1", bty = "n",
       legend = unique(MOI1), fill = unique(MOI1))

plot(x = MOI12diff, y = maxima["theory_I_with", ], ylim = c(0.5, 1), bty = "n",
     col = MOI1, pch = as.character(nMOI), ylab = "Maximum probability of reinfection",
     xlab = "MOI episode 1 - MOI episode 2")
text(y = 0.5, x = 2, adj = 1,
     labels = paste0("Number of episodes: ", paste(Episode_counts, collapse = " ")))
legend("right", title = "MOI of episode 1", bty = "n",
       legend = unique(MOI1), fill = unique(MOI1))

# Focusing in on cases where MOI episode 1 - MOI episode a2 = 0
# Trend is the same for both recrudescence and reinfection
# (number of potentially independent inter-episode edges for episodes 1 & 2)
plot(x = MOI2[MOI12diff == 0], bty = "n",
     y = maxima["theory_C_with", ][MOI12diff == 0],
     ylim = c(0.5, 1),
     col = MOI1[MOI12diff == 0], pch = as.character(nMOI[MOI12diff == 0]),
     xlab = "MOI of episodes 1 = 2", ylab = "Maximum probability of recrudescence")
text(y = 0.5, x = 2, labels = paste0("Number of episodes: ",
                                     paste(Episode_counts, collapse = " ")))
legend("right", title = "MOI of episode 1", fill = unique(nMOI[MOI12diff == 0]),
       legend = unique(nMOI[MOI12diff == 0]), bty = "n",)

plot(x = MOI2[MOI12diff == 0], bty = "n",
     y = maxima["theory_I_with", ][MOI12diff == 0],
     ylim = c(0.5, 1),
     col = MOI1[MOI12diff == 0], pch = as.character(nMOI[MOI12diff == 0]),
     xlab = "MOI of episodes 1 = 2", ylab = "Maximum probability of reinfection")
text(y = 0.5, x = 2, labels = paste0("Number of episodes: ",
                                     paste(Episode_counts, collapse = " ")))
legend("right", title = "MOI of episode 1", fill = unique(nMOI[MOI12diff == 0]),
       legend = unique(nMOI[MOI12diff == 0]), bty = "n")
