################################################################################
# Script to explore: how the maximum probability that a first recurrence is a
# recrudescence / reinfection varies with MOI vectors given data on the
# enrolment episode and the first recurrence only. The figures generated by this
# script feature in graph-prior.tex.
################################################################################
rm(list = ls())
all_MOIs <- sapply(colnames(maxima), function(x) as.numeric(strsplit(x, split = "")[[1]]))
maxMOIs <- sapply(all_MOIs, function(x) max(x))

# ==============================================================================
# General understanding of maximum probabilities
# ==============================================================================
nMOI <- sapply(all_MOIs, function(x) length(x)) # Number of episodes
MOI1 <- sapply(all_MOIs, function(x) x[1]) # MOI of episode one
MOI2 <- sapply(all_MOIs, function(x) x[2]) # MOI of episode two
MOI12diff <- sapply(all_MOIs, function(x) x[1] - x[2]) # Difference
MOI1s_log <- sapply(all_MOIs, function(x) all(x == 1)) # MOI vectors of all 1s
Episode_counts <- sort(unique(nMOI))

png("../vignettes/figures/maxima%d.png", width = 6, height = 6, units = "in", res = 300)

# Single recurrence reinfection
plot(x = MOI12diff[nMOI < 3], y = maxima["I_with", nMOI < 3], ylim = c(0.6, 1),
     bty = "n", bg = MOI1[nMOI < 3], col = MOI1[nMOI < 3], pch = 25, cex = 2,
     ylab = "Maximum probability of reinfection",
     xlab = "MOI episode 1 - MOI episode 2",
     panel.first = abline(v = 0))
legend("bottomleft", title = "MOI of episode 1", bty = "n", inset = 0.1,
       legend = unique(MOI1), fill = unique(MOI1))

# Single recurrence recrudescence
plot(x = MOI12diff[nMOI < 3], y = maxima["C_with", nMOI < 3], ylim = c(0.6, 1),
     bty = "n", col = MOI1[nMOI < 3], pch = 17, cex = 2,
     ylab = "Maximum probability of recrudescence",
     xlab = "MOI episode 1 - MOI episode 2",
     panel.first = abline(v = 0))
legend("bottomleft", title = "MOI of episode 1", bty = "n", inset = 0.1,
       legend = unique(MOI1), fill = unique(MOI1))

# Cases where the MOI is always one
plot(x = nMOI[MOI1s_log], y = maxima["C_with", MOI1s_log], bty = "n", cex = 2,
     type = "b", main = "", bg = "yellow", pch = 24, ylim = c(0.65, 0.85),
     xlab = "Number of monoclonal episodes",
     ylab = "Maximum probability of first recurrence")
lines(x = nMOI[MOI1s_log], y = maxima["I_with", MOI1s_log], cex = 2,
      type = "b", bg = "red", pch = 25)
legend("top", legend = c("Recrudescence", "Reinfection"), pch = c(24, 25),
       bt = "n", pt.bg = c("yellow","red"))

dev.off()
